language: node_js
node_js:
- 6.2.0
script: "./bin/test-unit.sh"
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: crpZw6Y2igoa1NsriYzI+2YPZAxw4L7M6f7gBXY7o/G9Hy0QIjAkn3XUITBxwCOXG2SNHnyI9BiUZpy2J5mf2qSQhvuiKNdRzBaPBk0NEF+n3x30+mfSUr7MMxzo1SW0BCwrgS/wgoTC5ebP+BKuUXdUrPMRNCX3gbJOgkkHEcYeH7UGu4utu8Jtc1divqGiowXgAsmLe6buwQzWLN3SBDsuPRznArGGtHAlb/DX4/Eaju4aqGhX68XVFJoY0VO32qHAPd5bnXoLbr2xeYjzP3rXPYqUv48eoR8C7LED7MrUtGdXX/mjNX0r3+jFucR6HeeyveW8V/BAJuyiPnO02bpq2ntQn9gPlQxO/7HYhEPI/aQRSHxz3kPwaO1jQCTqI8Y4Lv/qDJHUVDoMdOLsoM6zwgc8RV174PnWDz2ufv2pbc9GmFY444eZvj959JkOvrrwTQ7htmWrCQby0368Df6FgR9GLTKx15wjfmYWxLXCbkuKtSzG/1P+yX4HSKjtcICGiXWbJRUIlSMJf3PLdG4ikv8rckkrmwWfMs2hHgjeSSf9KU2GSIcUHfhe5Qak3JAfdzDEW/C8uXUAUkOLRa+G3vMenIbXYHfQoLG+zOYhvNI9FHoAUyoGH2YG/GmhT5doP3lYl3hgHmM1aHKr7VpSX8TLtgGBZOsRqppB0y4=
  app: ss-cart-api
  on:
    repo: devacto/product-service
